plugin: aws_ec2
regions: 
    - us-east-1
filters:
    tag:Name: JenkinsNode
    tag:ProjectName: capstone
    instance-state-name: running

keyed_groups:
  - prefix: dns
    key: 'public_dns'

compose:
    ansible_user: "'ubuntu'"