# CentOs instance
---
- name: "Configure ansible controller"
  hosts: all

  vars:
      epel_release_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      epel_dest: '/tmp/epel.rpm'

  tasks:
      - name: "Download epel package"
        get_url:
            url: "{{ epel_release_url }}"
            dest: "{{ epel_dest }}"

      - name: "Install epel"
        become: true
        yum:
            state: present
            update_cache: true
            name:
                - "{{ epel_dest }}"

      - name: "Install dependencies"
        become: true
        yum:
            state: present
            update_cache: true
            name:
                - 'python-pip'
                - 'ansible-2.9*'
                - 'unzip-6*'

      - name: Copy requirements
        copy:
            src: ansible_controller_requirements.txt
            dest: /tmp/requirements.txt

      - name: "Install pip requirements"
        become: true
        pip:
            state: present
            requirements: /tmp/requirements.txt

      - name: 'Copy ssh private key to remote host'
        copy:
            src: "{{ key_to_push }}"
            dest: '~/.ssh/instance_private_key.pem'
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0400'

      - name: "Zip local repo"
        delegate_to: 127.0.0.1
        archive:
            path: "{{ local_repo_root_dir }}"
            dest: '/tmp/archive_repo.zip'
            format: zip
      
      - name: "Make repo folder"
        file:
            state: directory
            path: '~/repo'

      - name: "Copy and unzip archive"
        unarchive:
            remote_src: false
            src: '/tmp/archive_repo.zip'
            dest: '~/repo'

      - name: "Copy controller address to localhost"
        delegate_to: 127.0.0.1
        copy:
            dest: '/tmp/ansible_controller_address'
            content: "{{ inventory_hostname }}"